import React from 'react';
import './page.scss';

const Page = () => {
    return (
        <div className="page">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe nobis nihil unde, minus accusantium magni, officiis error soluta repudiandae doloremque incidunt eligendi atque dolorum amet itaque vel labore. Tempore nihil asperiores in sint laboriosam, quam facere nemo. Neque ratione praesentium iste fugit voluptatibus eveniet, illum assumenda obcaecati tenetur eius sint nostrum itaque laborum error. Culpa at dolorem corrupti tempora. Odio iure voluptates sequi quia! Eum molestiae optio, doloribus unde iure quod, alias laborum dicta, ab sit recusandae distinctio! In magnam doloremque culpa mollitia ex eos, quos corporis rerum nemo nisi tenetur quae ducimus! Labore, necessitatibus? Minima facilis asperiores possimus illum quod ut excepturi ad dolor rerum, architecto repellendus non quas necessitatibus aliquid nemo. Cum sapiente quis delectus praesentium totam dolor alias, laboriosam obcaecati amet quisquam, quo aliquam animi ipsam libero deleniti ea harum numquam, aliquid neque. Incidunt magni in recusandae sapiente velit non totam expedita, excepturi facilis libero sit magnam alias numquam vel consectetur odit est exercitationem tenetur eaque aspernatur voluptates. Dolorum obcaecati dolore minima nemo excepturi fugit? Architecto accusamus minus in! Consequuntur, dolore saepe. Rem praesentium, error voluptatibus debitis deserunt explicabo, doloribus in aliquam architecto sed molestias animi vero est eveniet dicta. Provident magni illo quam asperiores excepturi nemo expedita laboriosam nulla earum assumenda aliquam ipsa, animi ut ea quia eveniet voluptas! Aliquid accusantium reprehenderit maxime. Eaque quam labore cumque eligendi ad deleniti animi eos, maiores in laborum adipisci, dolorum ex. Omnis, sapiente? Nobis praesentium, at fuga quo esse, asperiores aspernatur cumque expedita sapiente laboriosam inventore similique aut tempore delectus assumenda officia harum excepturi, accusamus minima illum? Neque, sint? Error, necessitatibus, eveniet commodi eaque ut quisquam id natus, blanditiis odit consequatur a! Vero odit aliquid assumenda nulla ad modi?</div>
    )
}

export default Page;